###

# List all service accounts

GET http://localhost:3000/service-accounts

###

# Add service account
POST http://localhost:3000/service-accounts
content-type: application/json

{
    "name": "me",
    "description": "None"
}

###

# Remove service account
DELETE  http://localhost:3000/service-accounts/123
content-type: application/json

###

# List all API keys

GET http://localhost:3000/api-keys

###

# Add API Key
POST http://localhost:3000/api-keys
content-type: application/json

{
    "serviceAccountId": "32171",
    "description": "for test delete at any time"
}

###

# Remove service account
DELETE  http://localhost:3000/api-keys/RWK552CQXLNDQ25K
content-type: application/json

###

# List all Access control lists

GET http://localhost:3000/access-control-lists

###

# Add Access control list
POST http://localhost:3000/access-control-lists
content-type: application/json

{
    "serviceAccountId": 993311,
    "allow": false,
    "operation": "CREATE",
    "topicPrefix": "testing.delete.at.any.time."
}

###

# Add Remove control list
DELETE  http://localhost:3000/access-control-lists
content-type: application/json

{
    "serviceAccountId": 993311,
    "allow": false,
    "operation": "CREATE",
    "topicPrefix": "testing.delete.at.any.time."
}